feat: added task generator
MapColonies/netSyncTasker pull request #1
Opened 2021-08-25 11:50 UTC by cl-shaharshavit-rnd

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✔                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✔                                                                        |
| Tests added     | ✔                                                                        |
| Chore            | ✖                                                                       |

Related issues: #XXX , #XXX ...
Closes #XXX ...

Further  information:

2021-08-25 14:24 UTC, asafMasa requested changes

2021-08-25 14:24 UTC, asafMasa commented on config/default.json
> +    "jobManagerUrl": "http://localhost",
add to config/custom-environment-variables.json

2021-08-25 14:24 UTC, asafMasa commented on config/default.json
> +    "taskType": "syncUploadBatch"
add to config/custom-environment-variables.json

2021-08-25 14:24 UTC, asafMasa commented on package.json
>    "description": "This is template for map colonies typescript service",
fix description

2021-08-25 14:24 UTC, asafMasa commented on src/common/constants.ts
> +export const SERVICE_NAME = 'net-sync-tasker';
why not to get it from the package.json file?

2021-08-25 14:24 UTC, asafMasa commented on src/containerConfig.ts
> +      return new JobManagerClient(logger, '', config.get('serviceClients.taskType'), config.get('serviceClients.jobManagerUrl'));
where is the jobType?

2021-08-25 14:24 UTC, asafMasa commented on src/index.ts
> +import { DEFAULT_SERVER_PORT, Services } from './common/constants';
why did you removed the traces?

2021-08-25 14:24 UTC, asafMasa commented on src/taskGenerator/models/taskManager.ts
> +    const footPrint = layer.metadata?.footprint as Polygon | Feature<Polygon> | Feature<MultiPolygon>;
rename footPrint -> footprint

2021-08-25 14:24 UTC, asafMasa commented on src/taskGenerator/models/taskManager.ts
> +    const zoom = degreesPerPixelToZoomLevel(layer.metadata?.resolution as number);
zoom -> zoomLevel

2021-08-25 14:24 UTC, asafMasa commented on src/taskGenerator/models/taskManager.ts
> +    const layer = await this.catalog.getDiscreteMetadata(resourceId, resourceVersion);
add info log

2021-08-25 14:24 UTC, asafMasa commented on src/taskGenerator/models/taskManager.ts
> +      await this.jobsClient.enqueueTask(jobId, {
add debug log

2021-08-26 05:53 UTC, cl-shaharshavit-rnd commented on src/common/constants.ts
> +export const SERVICE_NAME = 'net-sync-tasker';
1) this is the template
2) this is much faster and it will never change
3)this is much simpler (the require method from js will make the linter angry, you can't use import on json file, so 
 fs.readFileSync if the best method)

2021-08-26 05:55 UTC, cl-shaharshavit-rnd commented on src/containerConfig.ts
> +      return new JobManagerClient(logger, '', config.get('serviceClients.taskType'), config.get('serviceClients.jobManagerUrl'));
this service adds tasks to specified job so there is no need for jobType, it will never be used.
in addition this way you can have multiple types of jobs using the same service for tile batching

2021-08-26 05:57 UTC, cl-shaharshavit-rnd commented on src/index.ts
> +import { DEFAULT_SERVER_PORT, Services } from './common/constants';
it is bug in the template (i think it was fixed since). this instance of the tracing is never being used (the active tracer is in another file).

2021-08-26 07:01 UTC, asafMasa requested changes
add readme

2021-08-26 07:01 UTC, asafMasa commented on src/taskGenerator/models/tileBatcher.ts
> +        if (requiredForFullBatch > 0 && range.minY < range.maxY) {
explain the algorithm

2021-08-26 10:57 UTC, asafMasa approved these changes

2021-08-29 07:02 UTC, merged